# Generated by Django 6.0 on 2025-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automation",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
